# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161020_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='years_of_experience',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/images'),
        ),
    ]
