# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20161214_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='wiziq_credentials',
            field=models.TextField(blank=True, default='<p>\n        Usuario: ######## <br>\n        Password: ########\n        </p>'),
        ),
    ]
