# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0002_auto_20161013_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='transaction',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
