# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0004_auto_20161102_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='transaction',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_id',
            field=models.CharField(default='0', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('finished', 'Finished')], default='pending', max_length=10),
        ),
    ]
