# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='private_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
