# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20161110_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
