# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20161111_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrollment_date'], 'verbose_name': 'enrollment', 'verbose_name_plural': 'enrollments'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQs', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.IntegerField(choices=[(1, 'Principiante'), (2, 'Intermediate'), (3, 'Advanced')]),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('finished', 'Finished'), ('refunded', 'Refunded')], default='pending', max_length=10),
        ),
    ]
