# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20161116_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subtitle',
            field=models.CharField(default='Subtitulo para el curso', max_length=500),
            preserve_default=False,
        ),
    ]
