# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='details_document',
            field=models.FileField(default='hello', upload_to='courses/pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='extended_description',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
