# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20161207_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='materials',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='mentorship_sessions',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='proyects',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
