# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20161207_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='proyects',
            new_name='projects',
        ),
    ]
