# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20161208_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='next_session',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
