# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_next_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
